kind: pipeline
type: kubernetes
name: rt-emailer

platform:
  os: linux
  arch: amd64

trigger:
  event:
    - push

steps:
- name: set-automated-build-version
  pull: if-not-exists
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/rtge/scala-sbt:latest
  commands:
  - |
    set -eu

    APP_VERSION=$(grep -E '^version\s*:=' build.sbt | head -1 | sed -E 's/.*"([^"]+)".*/\1/')
    if [ -z "$APP_VERSION" ]; then
      echo "Unable to determine application version from build.sbt"
      exit 1
    fi

    BUILD_NUMBER="$${DRONE_BUILD_NUMBER}"
    APP_BASE_VERSION=$(echo "$${APP_VERSION}" | cut -d. -f1,2,3)
    GENERATED_APP_VERSION="$${APP_BASE_VERSION}-build.$${BUILD_NUMBER}"

    printf '%s\n' "$${GENERATED_APP_VERSION}" > .app-version

    echo "Base app version from build.sbt: $${APP_VERSION}"
    echo "Build number from Drone: $${BUILD_NUMBER}"
    echo "Generated app version: $${GENERATED_APP_VERSION}"

- name: ecr-login
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/dind-awscli:19.03.12-dind-1.18.55
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: aws_access_key_id
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret_access_key
  commands:
    # wait for docker service to be up before running docker build
    - n=0; while [ "$n" -lt 60 ] && [ ! docker stats --no-stream ]; do n=$(( n + 1 )); sleep 1; done
    - aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin 340268328991.dkr.ecr.eu-west-2.amazonaws.com
  volumes:
    - name: dockerclientconfig
      path: /root/.docker
  when:
    event:
      - push

- name: test_and_build
  pull: always
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/rtge/scala-sbt:latest
  commands:
  - . /app/entrypoint.sh
  - git config --global --list || true
  - git fetch --tags
  - sbt test
  - sbt clean coverageEnabled test coverageReport coverageOff
  #- sbt dependencyCheck
  #- sbt scapegoat || /bin/true
  - sbt clean assembly
  environment:
    ARTIFACTORY_PASSWORD:
      from_secret: DOCKER_PASSWORD
    ARTIFACTORY_USERNAME: regt-build-bot
    DB_HOST: "mongodatabase"
    JRE_VERSION: 24
    OVERRIDE_BUILD_REPOS: "false"
    HOME: "/app"
  when:
    event:
    - push
    - tag

- name: build_image
  pull: if-not-exists
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
  environment:
    AWS_REGION: eu-west-2
  commands:
    - |
      set -eu

      GENERATED_APP_VERSION=$(cat .app-version)
      
    - docker build -t rt-emailer:$${GENERATED_APP_VERSION} .
    - docker tag rt-emailer:$${GENERATED_APP_VERSION} rt-emailer:$${DRONE_COMMIT_SHA}
    - docker tag rt-emailer:$${GENERATED_APP_VERSION} rt-emailer:latest
  volumes:
    - name: dockerclientconfig
      path: /root/.docker
  depends_on:
    - test_and_build
    - ecr-login
  when:
    event:
      - push
      - tag

# https://docs.acp.homeoffice.gov.uk/how-to/security/trivy
- name: vulnerability-scan
  pull: always
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/trivy/client:latest
  resources:
    limits:
      cpu: 1000
      memory: 1024Mi
  environment:
    FAIL_ON_DETECTION: false
    IMAGE_NAME: rt-emailer:${DRONE_COMMIT_SHA}
    SEVERITY: MEDIUM,HIGH,CRITICAL
  when:
    branch:
    - master
    event:
    - push
  depends_on:
    - build_image

- name: push-build-image
  pull: if-not-exists
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
  commands:
    # wait for docker service to be up before running docker tag and push
    - n=0; while [ "$n" -lt 60 ] && [ ! docker stats --no-stream ]; do n=$(( n + 1 )); sleep 1; done
    - GENERATED_APP_VERSION=$(cat .app-version)

    # push the image from build_image up to ECR
    - docker tag rt-emailer:$${GENERATED_APP_VERSION} $${REGISTRY}/$${NAME}:$${GENERATED_APP_VERSION}
    - docker tag rt-emailer:$${DRONE_COMMIT_SHA} $${REGISTRY}/$${NAME}:$${DRONE_COMMIT_SHA}
    - docker tag rt-emailer:$${DRONE_COMMIT_SHA} $${REGISTRY}/$${NAME}:latest

    - docker push $${REGISTRY}/$${NAME}:$${GENERATED_APP_VERSION}
    - docker push $${REGISTRY}/$${NAME}:$${DRONE_COMMIT_SHA}
    - docker push $${REGISTRY}/$${NAME}:latest
  environment:
    AWS_REGION: eu-west-2
    NAME: rtge/rt-emailer
    REGISTRY: 340268328991.dkr.ecr.eu-west-2.amazonaws.com
  volumes:
    - name: dockerclientconfig
      path: /root/.docker
  when:
    event:
      - push
  depends_on:
    - build_image

- name: create-build-tag
  pull: if-not-exists
  image: node:20
  commands:
    - |
      set -eu

      UPDATED_APP_VERSION=$(cat .app-version)
      echo "UPDATED_APP_VERSION=$${UPDATED_APP_VERSION}"

      git config --global --list || true

      git tag -a "v$${UPDATED_APP_VERSION}" -m "Pipeline Build: v$${UPDATED_APP_VERSION}"
      git push origin "v$${UPDATED_APP_VERSION}"
  depends_on:
    - push-build-image
  when:
    # branch:
    #   - master
    event:
      - push


services:
- name: docker
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind

- name: mongodatabase
  pull: if-not-exists
  image: mongo:5.0

volumes:
  - name: dockerclientconfig
    temp: {}

