rules = [
  RemoveUnused,
  OrganizeImports,
  DisableSyntax
]

RemoveUnused.imports = true
RemoveUnused.privates = true
RemoveUnused.locals = true

OrganizeImports.groupedImports = Merge
OrganizeImports.removeUnused = true