version = "3.8.3"
runner.dialect = scala3

maxColumn = 80
indent.main = 2
indent.significant = 2

align.preset = most
align.multiline = false

newlines.source = keep
newlines.beforeCurlyLambdaParams = multilineWithCaseOnly
newlines.afterCurlyLambdaParams = squash

rewrite.rules = [RedundantBraces, SortImports, PreferCurlyFors]
rewrite.redundantBraces.stringInterpolation = true

docstrings.style = SpaceAsterisk
