version = "3.11.1"
runner.dialect = scala3

project.git = true
project.layout = StandardConvention
style = defaultWithAlign

maxColumn = 120
align.preset = "some"
align.allowOverflow = true
align.openParenDefnSite = false
align.openParenCallSite = false
align.tokens."+"                         = [
  {
    code   = "~>"
    owners = [
      { regex = "Term.ApplyInfix" }
    ]
  },
  {
    code   = "%"
    owners = [
      { regex = "Term.ApplyInfix" }
    ]
  },
  {
    code   = "%%"
    owners = [
      { regex = "Term.ApplyInfix" }
    ]
  }
]
danglingParentheses.preset = true

rewrite.rules = [RedundantBraces, RedundantParens, SortImports]
rewriteTokens = {
"⇒": "=>"
"→": "->"
"←": "<-"
}

spaces.inImportCurlyBraces = true

binPack.importSelectors = unfold
binPack.unsafeCallSite = false
binPack.unsafeDefnSite = false

fileOverride {
    "glob:**/*.sbt" {
        runner.dialect = sbt1
    }
}